---
- name: Get the list of services
  service_facts:

- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: services['firewalld.service'] is defined
...