---
- name: Start and enable tuned service
  service:
    name: tuned
    state: started
    enabled: yes

- name: Check if sap-netweaver was already activated
  command: "tuned-adm active"
  register: tuned_active
  changed_when: False

- name: Select sap-netweaver profile for tuned
  command: /usr/sbin/tuned-adm profile sap-netweaver
  when: "'sap-netweaver' not in tuned_active.stdout"
...
