---
- name: Set recommended kernel parameters for SAP HANA DB on RedHat 8
  sysctl:
    sysctl_file: /etc/sysctl.d/sap.conf
    name: "{{ kernel_param.name }}"
    value: "{{ kernel_param.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { name: vm.max_map_count, value: 2147483647 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 8192 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.core.rmem_max, value: 6291456 }
    - { name: net.core.wmem_max, value: 4194304 }
  loop_control:
    loop_var: kernel_param
...
