---
- name: sapbase.yml
  ansible.builtin.import_playbook: sapbase.yml
- name: saphana.yml
  ansible.builtin.import_playbook: saphana.yml
- name: javaci.yml
  ansible.builtin.import_playbook: javaci.yml
...